# Generated by Django 3.2 on 2022-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('series', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('genre', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('first_published_year', models.CharField(blank=True, max_length=254, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('isbn', models.CharField(blank=True, max_length=254, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
